winogrande:
  num_labels: 2
  report_ttac: [0.7, 0.8, 0.9]
  target_acc: 0.95

sst2:
  num_labels: 2
  report_ttac: [0.7, 0.8, 0.9]
  target_acc: 0.95

arc:
  num_labels: 4
  report_ttac: [0.4, 0.6, 0.7]
  target_acc: 0.7

hellaswag:
  num_labels: 4
  report_ttac: [0.5, 0.6, 0.7]
  target_acc: 0.8

piqa:
  num_labels: 2
  report_ttac: [0.5, 0.7, 0.8]
  target_acc: 0.85

mnli:
  num_labels: 3
  report_ttac: [0.4, 0.5, 0.6]
  target_acc: 0.6
